[workspace]
    authors   = ["CarbonPlan <hello@carbonplan.org>"]
    channels  = ["conda-forge"]
    name      = "srm-downscaling-data-utils"
    platforms = ["linux-64", "osx-arm64", "win-64"]
    version   = "0.1.0"

[tasks]

[dependencies]
    dask       = ">=2026.3.0,<2027"
    icechunk   = ">=2.0.5,<3"
    ipython    = ">=9.13.0,<10"
    jupyterlab = ">=4.5.7,<5"
    matplotlib = ">=3.10.9,<4"
    polars     = ">=1.41.0,<2"
    rasterio   = ">=1.5.0,<2"
    s3fs       = ">=2026.4.0,<2027"
    xarray     = ">=2026.4.0,<2027"
    xproj      = ">=0.2.1,<0.3"
    zarr       = ">=3.2.1,<4"

[pypi-dependencies]
    rasterix  = ">=0.2.1, <0.3"
    rusterize = ">=0.8.0, <0.9"
